### ISSUE TITLE
Getting a Device Allocation Error

### ISSUE THREAD

**Issue by AeroClassics** [kunzmi/managedCuda#8]
Michael,
What would cause such an error. It happens in my dynamic Jpeg version of you NPPJpeg sample. I guess I am not getting a device pointer. So far it does not seem to happen in the static version of the library.

ManagedCuda.NPP.NPPException was caught
  HResult=-2146233088
  Message=Device allocation error
  Source=NPP
  StackTrace:
       at ManagedCuda.NPP.NPPImage_8uC3..ctor(Int32 nWidthPixels, Int32 nHeightPixels) in d:\Develop\Github\managedCuda\NPP\NPPImage_8uC3.cs:line 59
       at NppImageUtils.JpegDecoder.JpegDecoder.Decoder(Byte[] pJpegData) in d:\AdVISE_Projects\NdtFileConverterEmgu\NPPImageUtils\JpegDecoder\JpegDecoder.cs:line 476
  InnerException:

**Comment by kunzmi** [comment]
Sounds like an out-of-memory problem. Do you run this in a loop and aren't freeing/disposing previous allocations?
